server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false # false表示自己为注册中心
    register-with-eureka: false  #表示是否向eureka注册中心注册自己
    service-url: #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


spring:
  application:
    name: spring-cloud-eureka