server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    fetch-registry: false # false表示自己为注册中心
    register-with-eureka: false  #表示是否向eureka注册中心注册自己
    service-url: #监控页面
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7002.com:7002/eureka/


spring:
  application:
    name: spring-cloud-eureka